---
- hosts: prod
  vars_files:
    - vars.yml
  become: true
  tasks:
    - name: upgrade all packages
      apt:
        upgrade: yes

    - name: install curl
      apt:
        name: curl

    - name: add nodejs repo to repolist
      shell: "curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -"

    - name: Install nodeJS
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Import the public key used by the package management system
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927
        state: present

    - name: Add MongoDB repository
      apt_repository:
        repo: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse'
        state: present

    - name: install mongodb
      apt:
        name: mongodb-org
        state: present
        force: yes
        update_cache: yes
      notify:
      - start mongodb

    - name: Install git
      apt:
        name: git
        state: present

    - name: clone src repo into /tmp
      git:
        repo: "{{ REPO }}"
        dest: /tmp/blog

    - name: Create the .env file
      copy:
        dest: "/tmp/blog/.env"
        content: "
          PORT={{ PORT }} \n
          DB_URL={{ DB_URL }} \n
          EXPRESS_SESSION_KEY={{ EXPRESS_SESSION_KEY }}"

    - name: ensure that bcrypt is peoperly working
      command: "npm install -g bcrypt"

  handlers:
  - name: start mongodb
    service:
      name: mongod
      state: started


